export  const CART_ACTIONS_TYPES = {
        SET_CART_ITEMS: 'SET_CART_ITEMS',
        SET_CART_COUNT:'SET_CART_COUNT',
        SET_CART_TOTAL:'SET_CART_TOTAL',
        TOGGLE_CART: 'TOGGLE_CART',
        ADD_CART_ITEM:'ADD_CART_ITEM',
        REMOVE_CART_ITEM:'REMOVE_CART_ITEM',
        DELETE_CART_ITEM: 'DELETE_CART_ITEM'
    }